config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    
    devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords', confirmations: 'users/confirmations' } 

    root to: 'home#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  #validates_presence_of :name, :father_name, :grandpa_name, :family_name, :birthday, :gender, :locality,
  #    :alley, :house_number, :neighborhood, :city, :state, :country, :cell_phone_number, :home_phone_number,
  #    :email

  #validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }    
  #validates_length_of :cell_phone_number, :minimum => 11, :maximum => 11

  devise :database_authenticatable, :confirmable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_locale
  before_action :authenticate_user!
  
  
  
  private
  
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
    #if params[:locale].present?
    #|| I18n.default_locale
    #Rails.application.routes.default_url_options[:locale]= I18n.locale
  end

  def default_url_options(options = {})
    {locale: I18n.locale}
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_nav.html.erb
<nav class="navbar fixed-top navbar-expand-sm navbar-inverse bg-dark">
  <div class="container">
    <div dir="auto">
      <ul class="nav navbar-nav pull-left">        
        <% if user_signed_in? %>
          <ul class="navbar-nav">
            <li class="nav-item">
              <div class= "nav-link"> 
                <h7><%= t 'views.user.new.hi' %></h7> <%= current_user.email %>
              </div>              
            </li>
            <li class="nav-item">
              <%= link_to t('views.user.new.log_out'), destroy_user_session_path, :method => :delete, class: "nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to t('views.user.new.edit_profile'), edit_user_registration_path,  class: "nav-link" %>
            </li>
          </ul>
        <% else%>
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to t('views.user.new.sign_up'), new_user_registration_path, class:  "nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to t('views.user.new.log_in'), new_user_session_path, class:  "nav-link"%>
            </li>
          </ul>
        <% end %>
      </ul>
    </div>
    
    <ul class="nav navbar-nav pull-right">
      <!-- Dropdown  
      -->
      <li class="nav-item dropdown">
        <div class="nav-link dropdown-toggle" data-toggle="dropdown" id="navbardrop">
          <%= t 'views.select_language'%>
        </div>
        <div class="dropdown-menu">
          <div class="dropdown-item"><%= link_to_unless I18n.locale == :en, "english", locale: :en %></div>
          <div class="dropdown-item"><%= link_to_unless I18n.locale == :ar, "العربية", locale: :ar %></div>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ByUser</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/nav" %>
      <br/>
      <br/>
      <br/>
      <br/>
      <center>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </center>  
    
      <%= yield %>
    
  </body>
</html>

app/views/users/_form.html.erb
<div class="container">
  <center> 
    <div dir="auto">  
      <%= form_with(model: user, local: true) do |form| %>
        <% if user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(user.errors.count, t('views.user.new.error')) %></h2>          
             
            <ul>
            <% user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        
        <div class="form-field">
          <div class="col-12 col-form-label">
            <div class="form-group row">                         
              <div class="field">
                <%= form.label :name %>
                <%= form.text_field :name, id: :user_name %>      
              </div>                 
              <div class="col">
                <div class="field">                  
                  <%= form.label :father_name %>                
                  <%= form.text_field :father_name, id: :user_name %>
                </div>
              </div>  
            </div>
          </div>
          <div class="col-12">
            <div class="form-group row"> 
              <div class="field">
                <%= form.label :grandpa_name %>
                <%= form.text_field :grandpa_name, id: :user_name %>
              </div>
              <div class="col">
                <div class="field">
                  <%= form.label :family_name %>
                  <%= form.text_field :family_name, id: :user_name %>
                </div>
              </div>
            </div>
          </div> 
          <div class="col-12">
            <div class="form-group row">   
              <div class="field">
                <%= form.label :birthday %>
                <%= form.date_field :birthday, id: :user_name %>
              </div>
              <div class="col">
                <div class="field">                  
                  <%= form.label :gender %>
                  <%= form.select :gender, [t('views.male'), t('views.female')], {include_blank: ""}, id: :user_name %>
                </div>
              </div>
            </div>
          </div>
          <div class="col-12">
            <div class="form-group row">   
              <div class="field">
                <%= form.label :locality %>
                <%= form.text_field :locality, id: :user_name %>
              </div>
              <div class="col">
                <div class="field">
                  <%= form.label :alley %>
                  <%= form.text_field :alley, id: :user_name %>
                </div>
              </div>
            </div>
          </div> 
          <div class="col-12">
            <div class="form-group row">  
              <div class="field">
                <%= form.label :house_number %>
                <%= form.text_field :house_number, id: :user_name %>
              </div>
              <div class="col">
                <div class="field">
                  <%= form.label :neighborhood %>
                  <%= form.text_field :neighborhood, id: :user_name %>
                </div>
              </div>
            </div>
          </div>
          <div class="col-12">
            <div class="form-group row">   
              <div class="field">
                <%= form.label :city %>
                <%= form.text_field :city, id: :user_name %>
              </div>
              <div class="col">
                <div class="field">
                  <%= form.label :state %>
                  <%= form.text_field :state, id: :user_name %>
                </div>
              </div>
            </div>
          </div>
          <div class="col-12">
            <div class="form-group row"> 
              <div class="field">
                <%= form.label :country %>
                <%= form.text_field :country, id: :user_name %>
              </div>
              <div class="col">
                <div class="field">
                  <%= form.label :email_address %>
                  <%= form.text_field :email_address, id: :user_name %>
                </div>
              </div>
            </div>
          </div>
          <div class="col-12">
            <div class="form-group row"> 
              <div class="field">
                <%= form.label :home_phone_number %>
                <%= form.text_field :home_phone_number, id: :user_name %>
                <span class="asterisk_input"></span>
              </div>
              <div class="col">
                <div class="field">
                  <%= form.label :cell_phone_number %>
                  <%= form.text_field :cell_phone_number, id: :user_name %>
                </div>
              </div>  
            </div>
          </div>  
             
          <div class="actions">
            <%= form.submit t('views.user.new.create_user') %>
          </div>
          <div class="btn">
            <%= link_to I18n.t('views.back'), users_path %>
          </div>
        </div>
      <% end %>
    </div>  
  </div>
</div>  

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>